
name: 'Auto Create Tag'
on:
  push:
    branches:
      - main
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: christophebedard/tag-version-commit@v1
        with:
          token: ${{ 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 }}
          version_regex: 'Release: ([0-9]+\.[0-9]+\.[0-9]+)'
          check_entire_commit_message: true
          version_tag_prefix: 'v'