name: Auto-tag on versionName change

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git
      run: |
        git config --global user.email "angga.riansah332@gmail.com"
        git config --global user.name "anggariansah"
        
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Get current versionName
      id: get_version
      run: echo "::set-output name=version::$(grep 'versionName' app/build.gradle | sed -n 's/.*versionName "\([^"]*\)".*/\1/p')"

    - name: Compare current versionName with previous version
      id: compare_versions
      run: echo "::set-output name=tag_required::$(test '${{ steps.get_version.outputs.version }}' != '$(cat previous_version.txt)'; echo $?)"

    - name: Tag repository
      if: steps.compare_versions.outputs.tag_required == '0'
      run: |
        echo "${{ steps.get_version.outputs.version }}" > previous_version.txt
        git tag -a v${{ steps.get_version.outputs.version }} -m "Release version ${{ steps.get_version.outputs.version }}"
        git push origin --tags
