name: Autotag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build with Gradle
        run: ./gradlew build

  tag:
    needs: build
    runs-on: ubuntu-latest

#    permissions:
#      issues: write
#      pull-requests: write
#      actions: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get the latest tag
        id: get_tag
        run: echo ::set-output name=TAG::$(git describe --abbrev=0 --tags)

      - name: Determine the next version
        id: version
        run: echo ::set-output name=NEW_VERSION::$(./gradlew -q printVersion)

      - name: Set up Git with PAT
        run: |
          git config user.email "angga.riansah332@gmail.com"
          git config user.name "anggariansah"
          git config credential.helper store

      - name: Log in with the PAT
        run: |
          git remote set-url origin https://${{ secrets.autotag }}@github.com/anggariansah/BarangBareng.git
          git fetch --tags

      - name: Create Tag
        id: create_tag
        run: git tag ${{ steps.version.outputs.NEW_VERSION }}

      - name: Push Tag
        run: git push origin ${{ steps.create_tag.outputs.NEW_VERSION }}
